version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
  celery:
    build: .
    command: celery -A main.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
